export const appActions = {
  APP_STARTED: 'APP_STARTED'
};

export const subjectActions = {
  ADD_SUBJECT: 'ADD_SUBJECT',
  EDIT_SUBJECT: 'EDIT_SUBJECT',
  DELETE_SUBJECT: 'DELETE_SUBJECT',
  UPDATE_STATE: 'UPDATE_STATE'
};

export const daybookActions = {
  ADD_EVENT: 'ADD_EVENT',
  EDIT_EVENT: 'EDIT_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
  UPDATE_STATE: 'UPDATE_STATE'
};
